Create components and add react Router for two pages.
jchernandez87/bookstore pull request #1
Opened 2021-08-23 22:55 UTC by jchernandez87

### Changes: 😃 

- Add NavBar component.
- Add Books component.
- Create AddBook component.
- Add categories page.
- Add routing for the two pages.
- Add Basic Styling to my components.

![](https://media1.giphy.com/media/jkSvCVEXWlOla/giphy.gif)

2021-08-23 23:43 UTC, oxenprogrammer requested changes
Hi **@jchernandez87** , 

Good job so far!
I can see you're really putting effort to become a world-class software developer :+1:
There are some issues that you still need to address in order to move forward to the next project.
Trust me you got this! :muscle:


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Consider the optional changes nice to have features and only work on them when you have satisfied the required changes_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-23 23:43 UTC, oxenprogrammer commented on README.md
> +[![LinkedIn][linkedin-shield]][linkedin-url]
**Nicely Done**
- [ ] This is a professional README file. Keep it up.

2021-08-23 23:43 UTC, oxenprogrammer commented on src/components/AddBook.css
> +}
**Nicly Done**
- [ ] Well done using modular CSS structure. Keep it up.

2021-08-23 23:43 UTC, oxenprogrammer commented on src/components/Books.js
> +        </div>
**Changes Required**
Well done using the `Array.proptype.map` method to iterate through the `BookInfo` iterable. However;
- [ ] The `div` with the `.container` should be a `Book.js` Component where each element of the `BookInfo` collection is passed as a prop to it according to the instructions. Please let us refactor it into `Book.js` component as it will aid in `lifting state` . This will allow changes in state to reflect in relevant components simultaneously.

2021-08-24 01:46 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashbaord. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-08-24 01:49 UTC, merged